# -*- Mode: YAML; indent-tabs-mode: nil; fill-column: 96; -*-
#pipe cat > meta/main.yml
---

galaxy_info:
  author: Thierry Delamare
  description: Install my dotemacs
  company: EpiConcept
  license: MIT
  min_ansible_version: 1.8
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  - name: Debian
    versions:
    - wheezy
  categories:
  - system
dependencies: []
#pipe cat > dotemacs-play.yml
---

- hosts: all

  vars:
    dotemacs:
      users:
        example:                # user name
          dir: my_dot_dir       # user dot files remote folder
          elisp: my_elisp_dir   # user elisp files remote folder
          volatil: basic        # which template to use for volatil ~/.emacs
          stable: servers       # which template to use for stable dotemacs
          file: my_dotemacs     # which file to use to generate stable dotemacs
          files: my_elisp_files # user elisp files local folder
        thy:                    # sane defaults apply

  roles:
    - .
#pipe cat > defaults/main.yml
---

# dynamic default via task
#dotemacs_dir: ~/.{{ ansible_ssh_user }}
dotemacs_elisp: elisp
dotemacs_volatil: dotemacs
dotemacs_stable: my-dotemacs
dotemacs_file: dotemacs.el
dotemacs_files: elisp

#pipe cat > tasks/main.yml
---

- assert:
    that:
      - ansible_ssh_user != 'root'
      - dotemacs.users[ansible_ssh_user] is defined

- set_fact:
    dir: ~/.{{ dotemacs.users[ansible_ssh_user].dir | default(ansible_ssh_user) }}
    elisp: |
      {{ dotemacs.users[ansible_ssh_user].elisp | default(dotemacs_elisp) }}
    volatil: |
      {{ dotemacs.users[ansible_ssh_user].volatil | default(dotemacs_volatil) }}.j2
    stable: |
      {{ dotemacs.users[ansible_ssh_user].stable | default(dotemacs_stable) }}.j2
    file: |
      {{ dotemacs.users[ansible_ssh_user].file | default(dotemacs_file) }}
    files: |
      {{ dotemacs.users[ansible_ssh_user].files | default(dotemacs_files) }}

- name: dotemacs - our dot dir
  file: path={{ dir }} state=directory

- name: dotemacs - allow check mode
  file: path={{ dir }} state=directory
  register: dirp

- set_fact: { dir_created: "{{ not dirp.changed }}" }

- name: dotemacs - our elisp dir
  file: path={{ dir }}/{{ elisp }} state=directory
  when: dir_created
  
- name: dotemacs - allow check mode
  file: path={{ dir }}/{{ elisp }} state=directory
  register: elispp

- set_fact: { elisp_created: "{{ not elispp.changed }}" }

- set_fact:
    local_dir: |
      {{ dir }}/{{ elisp }}
    local_file: |
      {{ dir }}/{{ file }}
      
- name: dotemacs - install volatil template
  template: src={{ volatil }} dest=~/.emacs

- name: dotemacs - install stable template
  template: src={{ stable }} dest={{ dir }}/{{ file }}

- name: dotemacs - install elisp files
  copy: src={{ files }}/ dest={{ dir }}/{{ elisp }}/
    
#pipe touch .stone
