#pipe cat > meta/main.yml
---

galaxy_info:
  author: Thierry Delamare
  description: Install my dotemacs
  company: EpiConcept
  license: MIT
  min_ansible_version: 2.3
  platforms:
  - name: Debian
    versions:
    - jessie
  categories:
  - system
dependencies: []
#pipe cat > dotemacs-play.yml
#!/usr/bin/env ansible-playbook
---

- hosts: all

  vars:
    dotemacs:
      users:
        example:                # user name
          dir: my_dot_dir       # user dot files remote folder
          elisp: my_elisp_dir   # user elisp files remote folder
          volatil: basic        # which template to use for volatil ~/.emacs
          stable: servers       # which template to use for stable dotemacs
          file: my_dotemacs     # which file to use to generate stable dotemacs
          files: my_elisp_files # user elisp files local folder
        thy:                    # sane defaults apply

  roles:
    - .
#pipe cat > defaults/main.yml
---

# dynamic default via task
#dotemacs_dir: ~/.{{ ansible_ssh_user }}
dotemacs_elisp: elisp
dotemacs_volatil: dotemacs
dotemacs_stable: my-dotemacs
dotemacs_file: dotemacs.el
dotemacs_files: elisp

#pipe cat > tasks/main.yml
---

- assert:
    that:
      - ansible_user_id != 'root'
      - dotemacs.users[ansible_user_id] is defined

- set_fact:
    dir: ~/.{{ dotemacs.users[ansible_user_id].dir | default(ansible_user_id) }}
    elisp: |-
      {{ dotemacs.users[ansible_user_id].elisp | default(dotemacs_elisp) }}
    volatil: |-
      {{ dotemacs.users[ansible_user_id].volatil | default(dotemacs_volatil) }}.j2
    stable: |-
      {{ dotemacs.users[ansible_user_id].stable | default(dotemacs_stable) }}.j2
    file: |-
      {{ dotemacs.users[ansible_user_id].file | default(dotemacs_file) }}
    files: |-
      {{ dotemacs.users[ansible_user_id].files | default(dotemacs_files) }}

- name: our dot dir
  file:
    path: '{{ dir }}'
    state: directory

- name: allow check mode
  file:
    path: '{{ dir }}'
    state: directory
  register: dirp

- set_fact: { dir_created: "{{ not dirp.changed }}" }

- name: our elisp dir
  file:
    path: '{{ dir }}/{{ elisp }}'
    state: directory
  when: dir_created
  
- name: allow check mode
  file:
    path: '{{ dir }}/{{ elisp }}'
    state: directory
  register: elispp

- set_fact: { elisp_created: "{{ not elispp.changed }}" }

- set_fact:
    local_dir: |-
      {{ dir }}/{{ elisp }}
    local_file: |-
      {{ dir }}/{{ file }}
      
- name: install volatil template
  template:
    src: '{{ volatil }}'
    dest: ~/.emacs

- name: install stable template
  template:
    src: '{{ stable }}'
    dest: '{{ dir }}/{{ file }}'

- name: install elisp files
  copy:
    src: '{{ files }}/'
    dest: '{{ dir }}/{{ elisp }}/'
    
#pipe touch .stone
