---

- assert:
    that:
      - ansible_user_id != 'root'
      - dotemacs.users[ansible_user_id] is defined

- set_fact:
    dir: ~/.{{ dotemacs.users[ansible_user_id].dir | default(ansible_user_id) }}
    elisp: |-
      {{ dotemacs.users[ansible_user_id].elisp | default(dotemacs_elisp) }}
    volatil: |-
      {{ dotemacs.users[ansible_user_id].volatil | default(dotemacs_volatil) }}.j2
    stable: |-
      {{ dotemacs.users[ansible_user_id].stable | default(dotemacs_stable) }}.j2
    file: |-
      {{ dotemacs.users[ansible_user_id].file | default(dotemacs_file) }}
    files: |-
      {{ dotemacs.users[ansible_user_id].files | default(dotemacs_files) }}

- name: our dot dir
  file:
    path: '{{ dir }}'
    state: directory

- name: allow check mode
  file:
    path: '{{ dir }}'
    state: directory
  register: dirp

- set_fact: { dir_created: "{{ not dirp.changed }}" }

- name: our elisp dir
  file:
    path: '{{ dir }}/{{ elisp }}'
    state: directory
  when: dir_created
  
- name: allow check mode
  file:
    path: '{{ dir }}/{{ elisp }}'
    state: directory
  register: elispp

- set_fact: { elisp_created: "{{ not elispp.changed }}" }

- set_fact:
    local_dir: |-
      {{ dir }}/{{ elisp }}
    local_file: |-
      {{ dir }}/{{ file }}
      
- name: install volatil template
  template:
    src: '{{ volatil }}'
    dest: ~/.emacs

- name: install stable template
  template:
    src: '{{ stable }}'
    dest: '{{ dir }}/{{ file }}'

- name: install elisp files
  copy:
    src: '{{ files }}/'
    dest: '{{ dir }}/{{ elisp }}/'
    
