(eval-when-compile    (require 'color-theme))
(defun my-color-theme ()
  "Color theme by Thierry Delamare, created 2014-03-19."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "#ffffff")
      (background-mode . light)
      (border-color . "black")
      (cursor-color . "#1a1a1a")
      (foreground-color . "#1a1a1a")
      (mouse-color . "#1a1a1a"))
     ((apropos-keybinding-face . underline)
      (apropos-label-face italic variable-pitch)
      (apropos-match-face . match)
      (apropos-property-face . bold-italic)
      (apropos-symbol-face . bold)
      (compilation-message-face . underline)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (rst-block-face . font-lock-keyword-face)
      (rst-comment-face . font-lock-comment-face)
      (rst-definition-face . font-lock-function-name-face)
      (rst-directive-face . font-lock-builtin-face)
      (rst-emphasis1-face quote italic)
      (rst-emphasis2-face quote bold)
      (rst-external-face . font-lock-type-face)
      (rst-level-face-base-color . "grey")
      (rst-literal-face . font-lock-string-face)
      (rst-reference-face . font-lock-variable-name-face)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "#ffffff" :foreground "#1a1a1a" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "dark blue"))))
     (compilation-column-number ((t (:foreground "ForestGreen"))))
     (compilation-error ((t (:bold t :weight bold :foreground "Red1"))))
     (compilation-info ((t (:bold t :foreground "Green3" :weight bold))))
     (compilation-line-number ((t (:foreground "sienna"))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-annotations ((t (:italic t :slant italic))))
     (completions-common-part ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#1a1a1a" :background "#ffffff" :stipple nil :height 98))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cursor ((t (nil))))
     (dired-directory ((t (:foreground "Blue1"))))
     (dired-flagged ((t (:bold t :weight bold :foreground "Red1"))))
     (dired-header ((t (:foreground "ForestGreen"))))
     (dired-ignored ((t (:foreground "grey50"))))
     (dired-mark ((t (:foreground "dark cyan"))))
     (dired-marked ((t (:bold t :weight bold :foreground "Red1"))))
     (dired-perm-write ((t (:foreground "Firebrick"))))
     (dired-symlink ((t (:foreground "Purple"))))
     (dired-warning ((t (:bold t :weight bold :foreground "Red1"))))
     (erin-address-link-face ((t (:background "#ddddff" :foreground "blue" :underline t))))
     (erin-address-nonlink-face ((t (:background "#ddddff" :foreground "black" :underline nil :slant normal :weight normal))))
     (erin-bold-face ((t (:bold t :weight bold))))
     (erin-bold-fixed-face ((t (:bold t :background "#ffdd00" :foreground "black" :weight bold))))
     (erin-bold-italic-face ((t (:italic t :bold t :slant italic :weight bold))))
     (erin-bullet-face ((t (:bold t :foreground "red4" :weight bold))))
     (erin-deemph-markup-face ((t (:foreground "gray75" :underline nil :slant normal :weight normal))))
     (erin-fixed-face ((t (:background "#ffdd00" :foreground "black"))))
     (erin-heading-1-face ((t (:bold t :weight bold :height 2.48832 :family "Helvetica"))))
     (erin-heading-2-face ((t (:bold t :weight bold :height 2.0736 :family "Helvetica"))))
     (erin-heading-3-face ((t (:bold t :weight bold :height 1.728 :family "Helvetica"))))
     (erin-heading-4-face ((t (:bold t :weight bold :height 1.44 :family "Helvetica"))))
     (erin-heading-5-face ((t (:bold t :weight bold :height 1.2 :family "Helvetica"))))
     (erin-heading-6-face ((t (:bold t :weight bold :height 1.0 :family "Helvetica"))))
     (erin-italic-face ((t (:italic t :slant italic))))
     (erin-markup-face ((t (:bold t :foreground "gray50" :weight bold))))
     (erin-nonaddress-link-face ((t (:foreground "blue" :underline t))))
     (erin-normal-face ((t (nil))))
     (erin-prominent-markup-face ((t (:bold t :foreground "red4" :weight bold))))
     (erin-separator-face ((t (:bold t :foreground "red4" :weight bold))))
     (erin-variable-face ((t (:bold t :background "#40ff40" :foreground "black" :weight bold))))
     (erin-variable-parameters-face ((t (:background "#40ff40" :foreground "black" :weight normal))))
     (escape-glyph ((t (:foreground "brown"))))
     (file-name-shadow ((t (:foreground "grey50"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (font-lock-builtin-face ((t (:foreground "MediumOrchid4"))))
     (font-lock-comment-delimiter-face ((t (:foreground "Firebrick"))))
     (font-lock-comment-face ((t (:foreground "Firebrick"))))
     (font-lock-constant-face ((t (:foreground "dark cyan"))))
     (font-lock-doc-face ((t (:foreground "VioletRed4"))))
     (font-lock-function-name-face ((t (:foreground "Blue1"))))
     (font-lock-keyword-face ((t (:foreground "Purple"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "MediumOrchid4"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "VioletRed4"))))
     (font-lock-type-face ((t (:foreground "ForestGreen"))))
     (font-lock-variable-name-face ((t (:foreground "sienna"))))
     (font-lock-warning-face ((t (:bold t :foreground "Red1" :weight bold))))
     (fringe ((t (:background "grey95"))))
     (header-line ((t (:box (:line-width -1 :style released-button) :background "grey90" :foreground "grey20" :box nil))))
     (help-argument-name ((t (:italic t :slant italic))))
     (highlight ((t (:background "darkseagreen2"))))
     (isearch ((t (:background "magenta3" :foreground "lightskyblue1"))))
     (isearch-fail ((t (:background "RosyBrown1"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "paleturquoise"))))
     (link ((t (:foreground "blue1" :underline t))))
     (link-visited ((t (:underline t :foreground "magenta4"))))
     (match ((t (:background "yellow1"))))
     (menu ((t (nil))))
     (minibuffer-prompt ((t (:foreground "medium blue"))))
     (mmm-cleanup-submode-face ((t (:background "Wheat"))))
     (mmm-code-submode-face ((t (:background "LightGray"))))
     (mmm-comment-submode-face ((t (:background "SkyBlue"))))
     (mmm-declaration-submode-face ((t (:background "Aquamarine"))))
     (mmm-default-submode-face ((t (:background "gray85"))))
     (mmm-delimiter-face ((t (nil))))
     (mmm-init-submode-face ((t (:background "Pink"))))
     (mmm-output-submode-face ((t (:background "Plum"))))
     (mmm-special-submode-face ((t (:background "MediumSpringGreen"))))
     (mode-line ((t (:background "grey75" :foreground "#000000" :box (:line-width -1 :style released-button)))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "grey90" :foreground "grey20" :box (:line-width -1 :color "grey75" :style nil) :weight light))))
     (mouse ((t (nil))))
     (next-error ((t (:background "lightgoldenrod2"))))
     (nobreak-space ((t (:foreground "brown" :underline t))))
     (pp^L-highlight ((t (:box (:line-width 3 :style pressed-button)))))
     (query-replace ((t (:foreground "lightskyblue1" :background "magenta3"))))
     (region ((t (:background "lightgoldenrod2"))))
     (rst-level-1-face ((t (:background "grey85"))))
     (rst-level-2-face ((t (:background "grey78"))))
     (rst-level-3-face ((t (:background "grey71"))))
     (rst-level-4-face ((t (:background "grey64"))))
     (rst-level-5-face ((t (:background "grey57"))))
     (rst-level-6-face ((t (:background "grey50"))))
     (scroll-bar ((t (:background "#edeceb" :foreground "#000000"))))
     (secondary-selection ((t (:background "yellow1"))))
     (sgml-namespace ((t (:foreground "MediumOrchid4"))))
     (shadow ((t (:foreground "grey50"))))
     (show-tabs-space ((t (:background "yellow1"))))
     (show-tabs-tab ((t (:background "red1"))))
     (tool-bar ((t (:background "#edeceb" :foreground "#000000" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "dark green"))))
     (widget-field ((t (:background "gray85"))))
     (widget-inactive ((t (:foreground "grey50"))))
     (widget-single-line-field ((t (:background "gray85"))))
     (yaml-tab-face ((t (:bold t :background "red" :foreground "red" :weight bold)))))))
(add-to-list 'color-themes '(my-color-theme  "THEME NAME" "YOUR NAME"))
